name: Team awesome's approval workflow
on:
  pull_request:
    types:
      - labeled
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment on PR
        uses: ./.github/actions/commentOnPR
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
